project:
    type: book
    output-dir: public
    execute-dir: project

book:
    title: "Reproducible Research in R"
    subtitle: "An advanced workshop on creating collaborative and automated analysis pipelines"
    author:
        - "Luke W. Johnston"
    favicon: "images/favicon.ico"
    site-url: "https://r-cubed-advanced.rostools.org"
    repo-url: "https://github.com/rostools/r-cubed-advanced"
    repo-branch: main
    repo-actions: [edit, issue, source]
    search:
        location: navbar
        type: overlay
    chapters:
        - index.qmd
        - content/00-syllabus.qmd
        - content/00-schedule.qmd
        - content/00-pre-course.qmd
    appendices:
        - appendix/conduct.qmd
    page-footer:
        center:
            - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
              href: LICENSE.md

bibliography: includes/references.bib

format:
  html:
    df-print: tibble
    from: markdown+emoji
    code-link: true
    theme:
        - litera
        - includes/theme.scss
    include-before-body:
        - "includes/site-counter.html"
        - "includes/contribute.html"
  # docx:
  #   toc: false
  #   from: markdown+emoji

knitr:
  opts_chunk:
    width: 68
    # maybe?
    collapse: true
    comment: "#>"
    # Use this to set class for output?
    # cell-output: ....
