project:
  type: book
  output-dir: public
  execute-dir: project
  pre-render: quarto render slides/*.qmd

book:
  title: "Reproducible Research in R"
  subtitle: "An advanced workshop on creating collaborative and automated analysis pipelines"
  author:
    - "Luke W. Johnston"
  favicon: "images/favicon.ico"
  site-url: "https://r-cubed-advanced.rostools.org"
  repo-url: "https://github.com/rostools/r-cubed-advanced"
  repo-branch: main
  repo-actions: [edit, issue, source]
  search:
    location: navbar
    type: overlay
  chapters:
    - index.qmd
    - part: "Preamble"
      chapters:
      - preamble/syllabus.qmd
      - preamble/schedule.qmd
      - preamble/pre-course.qmd
    - part: "Sessions"
      chapters:
      - sessions/introduction.qmd
      - sessions/smoother-collaboration.qmd
      - sessions/pipelines.qmd
  appendices:
    - appendix/conduct.qmd
    - appendix/connect-github.qmd
    - appendix/resources.qmd
    - appendix/references.qmd
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.md

bibliography:
  - includes/references.bib
  - includes/packages.bib
csl: includes/vancouver.csl
callout-appearance: simple
reference-location: margin
citation-location: margin
crossref:
  chapters: true

editor_options:
  markdown:
  wrap: 72
  canonical: true

format:
  html:
    df-print: tibble
    code-overflow: scroll
    from: markdown+emoji
    code-link: true
    theme:
      - litera
      - includes/theme.scss
    include-before-body:
      - "includes/site-counter.html"
      - "includes/contribute.html"
  # docx:
  #   toc: false
  #   from: markdown+emoji

knitr:
  opts_chunk:
    width: 68
    comment: ""
    class-output: sourceCode
